blank_issues_enabled: false
contact_links:
  - name: SMAPI Version
    url: https://smapi.io
    about: Do you have the latest version of SMAPI? Make sure you do before submitting an issue.
  - name: UIInfoSuite2 Releases
    url: https://github.com/Annosz/UIInfoSuite2/releases
    about: Make sure you have the latest release of the mod!
  - name: Log Report
    url: https://smapi.io/log
    about: Make sure to upload your logs before making an issue about a game-breaking bug.
